---

- name: Install metricbeat 
  become: true 
  shell: | 
    curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.5.2-amd64.deb 
    dpkg -i metricbeat-7.5.2-amd64.deb

- name: Render metricbeat config
  template: 
    src: metricbeat.yml.j2
    dest: /etc/metricbeat/metricbeat.yml

- name: Enable metricbeat 
  become: true 
  shell: |
    metricbeat modules enable aws
    metricbeat setup
    service metricbeat start